# Generated by Django 4.2.4 on 2023-08-31 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='spirit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('young_crue', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=50)),
                ('water_baptem', models.CharField(max_length=3)),
                ('spirit_baptem', models.CharField(max_length=3)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='scolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_level', models.CharField(max_length=50)),
                ('last_diplom', models.CharField(max_length=50)),
                ('type_bac', models.CharField(max_length=1)),
                ('fields', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='professionnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working', models.CharField(max_length=3)),
                ('jobs', models.CharField(max_length=80)),
                ('jobs_description', models.TextField(blank=True, default=None)),
                ('cv', models.FileField(null=True, upload_to='PDF/CV/')),
                ('image_de_profil', models.ImageField(null=True, upload_to='Pictures/profil')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('living_town', models.CharField(max_length=50)),
                ('commune', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=15)),
                ('domaines', models.CharField(max_length=80)),
                ('genre', models.CharField(max_length=10)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
